name: multi event test

on: 
  issues:
  pull_request:

jobs:
  my_job_1 :
    runs-on: ubuntu-latest
    steps: 
      - name: run a command
        run: |
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
  
  my_job_2 :
    runs-on: ubuntu-latest
    steps:
      - name: say my name
        run: echo "my name is $(whoami)"

