

on:
    push:

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: checkout to branch
              uses: actions/checkout@v4

            - name: fetch secret
              run: echo "secret value is ${{ secrets.NAME}}"
              